#############################################################################
# Makefile for building: gameNetwork
# Generated by qmake (2.01a) (Qt 4.8.4) on: ?? 4? 20 14:26:42 2015
# Project:  gameNetwork.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/local/Qt4.8/mkspecs/unsupported/macx-clang -o Makefile gameNetwork.pro
#############################################################################

####### Compiler, tools and options

CC            = clang
CXX           = clang++
DEFINES       = 
CFLAGS        = -pipe -g -gdwarf-2 -arch x86_64 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -g -O0 -std=c++0x -mmacosx-version-min=10.7 -stdlib=libc++ -W -Wno-unused-parameter -gdwarf-2 -arch x86_64 $(DEFINES) -g -gdwarf-2 -arch x86_64 $(DEFINES)
INCPATH       = -I/usr/local/Qt4.8/mkspecs/unsupported/macx-clang -I. -Isdu -Inewlist -ITransfer -Ideps/tinyxml -Ideps/fd -Ideps -Ideps/curlpp-0.7.3/include -I/usr/local/include -I/System/Library/Frameworks/Python.framework/Versions//include/python -I/usr/include -I/usr/local/include
LINK          = clang++
LFLAGS        = -headerpad_max_install_names -mmacosx-version-min=10.7 -stdlib=libc++ -arch x86_64
LIBS          = $(SUBLIBS)   -lcurl -lzmq -lpython -L/usr/lib -lboost_thread -lboost_system -lboost_program_options -lboost_python -L/usr/local/lib 
AR            = ar cq
RANLIB        = ranlib -s
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = 
INSTALL_FILE  = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = $(COPY_FILE)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
export MACOSX_DEPLOYMENT_TARGET = 10.4

####### Output directory

OBJECTS_DIR   = tmp/

####### Files

SOURCES       = main.cpp \
		GameHolder.cpp \
		newlist/DataClientSocket.cpp \
		newlist/Mutex.cpp \
		newlist/ServerClientSocket.cpp \
		newlist/Socket.cpp \
		newlist/SocketDefines.cpp \
		newlist/SocketMgr.cpp \
		newlist/SocketOps.cpp \
		newlist/ThreadPool.cpp \
		sdu/Logging.cpp \
		sdu/md5.cpp \
		Transfer/bnfgameproto.cpp \
		Transfer/netdata.cpp \
		sdu/sdtime.cpp \
		sdu/sdstring.cpp \
		sdu/sdlog.cpp 
OBJECTS       = tmp/main.o \
		tmp/GameHolder.o \
		tmp/DataClientSocket.o \
		tmp/Mutex.o \
		tmp/ServerClientSocket.o \
		tmp/Socket.o \
		tmp/SocketDefines.o \
		tmp/SocketMgr.o \
		tmp/SocketOps.o \
		tmp/ThreadPool.o \
		tmp/Logging.o \
		tmp/md5.o \
		tmp/bnfgameproto.o \
		tmp/netdata.o \
		tmp/sdtime.o \
		tmp/sdstring.o \
		tmp/sdlog.o
DIST          = /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/clang.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.8/mkspecs/features/debug.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf \
		gameNetwork.pro
QMAKE_TARGET  = gameNetwork
DESTDIR       = 
TARGET        = gameNetwork

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-g \
		-arch \
		x86_64 \
		-Wall \
		-W


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: gameNetwork.pro  /usr/local/Qt4.8/mkspecs/unsupported/macx-clang/qmake.conf /usr/local/Qt4.8/mkspecs/common/unix.conf \
		/usr/local/Qt4.8/mkspecs/common/mac.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base.conf \
		/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf \
		/usr/local/Qt4.8/mkspecs/common/clang.conf \
		/usr/local/Qt4.8/mkspecs/qconfig.pri \
		/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Qt4.8/mkspecs/features/qt_functions.prf \
		/usr/local/Qt4.8/mkspecs/features/qt_config.prf \
		/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf \
		/usr/local/Qt4.8/mkspecs/features/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf \
		/usr/local/Qt4.8/mkspecs/features/debug.prf \
		/usr/local/Qt4.8/mkspecs/features/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf \
		/usr/local/Qt4.8/mkspecs/features/warn_on.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/rez.prf \
		/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf \
		/usr/local/Qt4.8/mkspecs/features/resources.prf \
		/usr/local/Qt4.8/mkspecs/features/uic.prf \
		/usr/local/Qt4.8/mkspecs/features/yacc.prf \
		/usr/local/Qt4.8/mkspecs/features/lex.prf \
		/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/unsupported/macx-clang -o Makefile gameNetwork.pro
/usr/local/Qt4.8/mkspecs/common/unix.conf:
/usr/local/Qt4.8/mkspecs/common/mac.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base.conf:
/usr/local/Qt4.8/mkspecs/common/gcc-base-macx.conf:
/usr/local/Qt4.8/mkspecs/common/clang.conf:
/usr/local/Qt4.8/mkspecs/qconfig.pri:
/usr/local/Qt4.8/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Qt4.8/mkspecs/features/qt_functions.prf:
/usr/local/Qt4.8/mkspecs/features/qt_config.prf:
/usr/local/Qt4.8/mkspecs/features/exclusive_builds.prf:
/usr/local/Qt4.8/mkspecs/features/default_pre.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_pre.prf:
/usr/local/Qt4.8/mkspecs/features/mac/dwarf2.prf:
/usr/local/Qt4.8/mkspecs/features/debug.prf:
/usr/local/Qt4.8/mkspecs/features/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/default_post.prf:
/usr/local/Qt4.8/mkspecs/features/mac/objective_c.prf:
/usr/local/Qt4.8/mkspecs/features/mac/x86_64.prf:
/usr/local/Qt4.8/mkspecs/features/warn_on.prf:
/usr/local/Qt4.8/mkspecs/features/mac/rez.prf:
/usr/local/Qt4.8/mkspecs/features/mac/sdk.prf:
/usr/local/Qt4.8/mkspecs/features/resources.prf:
/usr/local/Qt4.8/mkspecs/features/uic.prf:
/usr/local/Qt4.8/mkspecs/features/yacc.prf:
/usr/local/Qt4.8/mkspecs/features/lex.prf:
/usr/local/Qt4.8/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec /usr/local/Qt4.8/mkspecs/unsupported/macx-clang -o Makefile gameNetwork.pro

dist: 
	@$(CHK_DIR_EXISTS) tmp/gameNetwork1.0.0 || $(MKDIR) tmp/gameNetwork1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) tmp/gameNetwork1.0.0/ && (cd `dirname tmp/gameNetwork1.0.0` && $(TAR) gameNetwork1.0.0.tar gameNetwork1.0.0 && $(COMPRESS) gameNetwork1.0.0.tar) && $(MOVE) `dirname tmp/gameNetwork1.0.0`/gameNetwork1.0.0.tar.gz . && $(DEL_FILE) -r tmp/gameNetwork1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

tmp/main.o: main.cpp GameHolder.h \
		Transfer/ProtocolDefine.h \
		sdu/sdtype.h \
		sdu/buildconfig.h \
		Transfer/bnfgameproto.h \
		Transfer/netdata.h \
		newlist/ByteBuffer.h \
		newlist/Mutex.h \
		newlist/FastQueue.h \
		newlist/ServerClientSocket.h \
		newlist/Network.h \
		newlist/Common.h \
		newlist/Singleton.h \
		newlist/Threading.h \
		newlist/ThreadStarter.h \
		newlist/ThreadPool.h \
		newlist/BaseBuffer.h \
		newlist/StraightBuffer.h \
		newlist/Socket.h \
		newlist/BaseSocket.h \
		newlist/SocketOps.h \
		newlist/SocketDefines.h \
		newlist/SocketMgr.h \
		newlist/ListenSocket.h \
		newlist/DataClientSocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/main.o main.cpp

tmp/GameHolder.o: GameHolder.cpp GameHolder.h \
		Transfer/ProtocolDefine.h \
		sdu/sdtype.h \
		sdu/buildconfig.h \
		Transfer/bnfgameproto.h \
		Transfer/netdata.h \
		newlist/ByteBuffer.h \
		newlist/Mutex.h \
		newlist/FastQueue.h \
		newlist/Network.h \
		newlist/Common.h \
		newlist/Singleton.h \
		newlist/Threading.h \
		newlist/ThreadStarter.h \
		newlist/ThreadPool.h \
		newlist/BaseBuffer.h \
		newlist/StraightBuffer.h \
		newlist/Socket.h \
		newlist/BaseSocket.h \
		newlist/SocketOps.h \
		newlist/SocketDefines.h \
		newlist/SocketMgr.h \
		newlist/ListenSocket.h \
		newlist/ServerClientSocket.h \
		newlist/DataClientSocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/GameHolder.o GameHolder.cpp

tmp/DataClientSocket.o: newlist/DataClientSocket.cpp newlist/DataClientSocket.h \
		newlist/Network.h \
		newlist/Common.h \
		newlist/Singleton.h \
		sdu/buildconfig.h \
		newlist/Threading.h \
		newlist/Mutex.h \
		newlist/ThreadStarter.h \
		newlist/ThreadPool.h \
		newlist/BaseBuffer.h \
		newlist/StraightBuffer.h \
		newlist/Socket.h \
		newlist/BaseSocket.h \
		newlist/SocketOps.h \
		newlist/SocketDefines.h \
		newlist/SocketMgr.h \
		newlist/ListenSocket.h \
		newlist/FastQueue.h \
		newlist/ServerClientSocket.h \
		Transfer/ProtocolDefine.h \
		sdu/sdtype.h \
		Transfer/bnfgameproto.h \
		Transfer/netdata.h \
		newlist/ByteBuffer.h \
		GameHolder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/DataClientSocket.o newlist/DataClientSocket.cpp

tmp/Mutex.o: newlist/Mutex.cpp newlist/Mutex.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/Mutex.o newlist/Mutex.cpp

tmp/ServerClientSocket.o: newlist/ServerClientSocket.cpp newlist/ServerClientSocket.h \
		Transfer/ProtocolDefine.h \
		sdu/sdtype.h \
		sdu/buildconfig.h \
		Transfer/bnfgameproto.h \
		Transfer/netdata.h \
		newlist/Network.h \
		newlist/Common.h \
		newlist/Singleton.h \
		newlist/Threading.h \
		newlist/Mutex.h \
		newlist/ThreadStarter.h \
		newlist/ThreadPool.h \
		newlist/BaseBuffer.h \
		newlist/StraightBuffer.h \
		newlist/Socket.h \
		newlist/BaseSocket.h \
		newlist/SocketOps.h \
		newlist/SocketDefines.h \
		newlist/SocketMgr.h \
		newlist/ListenSocket.h \
		newlist/ByteBuffer.h \
		newlist/DataClientSocket.h \
		newlist/FastQueue.h \
		GameHolder.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/ServerClientSocket.o newlist/ServerClientSocket.cpp

tmp/Socket.o: newlist/Socket.cpp newlist/Common.h \
		newlist/Singleton.h \
		sdu/buildconfig.h \
		newlist/Network.h \
		newlist/Threading.h \
		newlist/Mutex.h \
		newlist/ThreadStarter.h \
		newlist/ThreadPool.h \
		newlist/BaseBuffer.h \
		newlist/StraightBuffer.h \
		newlist/Socket.h \
		newlist/BaseSocket.h \
		newlist/SocketOps.h \
		newlist/SocketDefines.h \
		newlist/SocketMgr.h \
		newlist/ListenSocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/Socket.o newlist/Socket.cpp

tmp/SocketDefines.o: newlist/SocketDefines.cpp newlist/SocketDefines.h \
		newlist/Common.h \
		newlist/Singleton.h \
		sdu/buildconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/SocketDefines.o newlist/SocketDefines.cpp

tmp/SocketMgr.o: newlist/SocketMgr.cpp newlist/Common.h \
		newlist/Singleton.h \
		sdu/buildconfig.h \
		newlist/Network.h \
		newlist/Threading.h \
		newlist/Mutex.h \
		newlist/ThreadStarter.h \
		newlist/ThreadPool.h \
		newlist/BaseBuffer.h \
		newlist/StraightBuffer.h \
		newlist/Socket.h \
		newlist/BaseSocket.h \
		newlist/SocketOps.h \
		newlist/SocketDefines.h \
		newlist/SocketMgr.h \
		newlist/ListenSocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/SocketMgr.o newlist/SocketMgr.cpp

tmp/SocketOps.o: newlist/SocketOps.cpp newlist/Common.h \
		newlist/Singleton.h \
		sdu/buildconfig.h \
		newlist/Network.h \
		newlist/Threading.h \
		newlist/Mutex.h \
		newlist/ThreadStarter.h \
		newlist/ThreadPool.h \
		newlist/BaseBuffer.h \
		newlist/StraightBuffer.h \
		newlist/Socket.h \
		newlist/BaseSocket.h \
		newlist/SocketOps.h \
		newlist/SocketDefines.h \
		newlist/SocketMgr.h \
		newlist/ListenSocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/SocketOps.o newlist/SocketOps.cpp

tmp/ThreadPool.o: newlist/ThreadPool.cpp newlist/ThreadPool.h \
		newlist/Mutex.h \
		newlist/ThreadStarter.h \
		newlist/Common.h \
		newlist/Singleton.h \
		sdu/buildconfig.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/ThreadPool.o newlist/ThreadPool.cpp

tmp/Logging.o: sdu/Logging.cpp sdu/SDuPCH.h \
		sdu/buildconfig.h \
		sdu/buildinclude.h \
		sdu/Assertion.h \
		sdu/Logging.h \
		sdu/sdsingleton.h \
		sdu/Print.h \
		sdu/sdtime.h \
		sdu/sdtype.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/Logging.o sdu/Logging.cpp

tmp/md5.o: sdu/md5.cpp sdu/md5.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/md5.o sdu/md5.cpp

tmp/bnfgameproto.o: Transfer/bnfgameproto.cpp Transfer/bnfgameproto.h \
		Transfer/netdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/bnfgameproto.o Transfer/bnfgameproto.cpp

tmp/netdata.o: Transfer/netdata.cpp Transfer/netdata.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/netdata.o Transfer/netdata.cpp

tmp/sdtime.o: sdu/sdtime.cpp sdu/SDuPCH.h \
		sdu/buildconfig.h \
		sdu/buildinclude.h \
		sdu/Assertion.h \
		sdu/Logging.h \
		sdu/sdsingleton.h \
		sdu/Print.h \
		sdu/sdtime.h \
		sdu/sdtype.h \
		sdu/sdstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/sdtime.o sdu/sdtime.cpp

tmp/sdstring.o: sdu/sdstring.cpp sdu/SDuPCH.h \
		sdu/buildconfig.h \
		sdu/buildinclude.h \
		sdu/Assertion.h \
		sdu/Logging.h \
		sdu/sdsingleton.h \
		sdu/Print.h \
		sdu/sdstring.h \
		sdu/sdtype.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/sdstring.o sdu/sdstring.cpp

tmp/sdlog.o: sdu/sdlog.cpp sdu/SDuPCH.h \
		sdu/buildconfig.h \
		sdu/buildinclude.h \
		sdu/Assertion.h \
		sdu/Logging.h \
		sdu/sdsingleton.h \
		sdu/Print.h \
		sdu/sdlog.h \
		sdu/sdtime.h \
		sdu/sdtype.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tmp/sdlog.o sdu/sdlog.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

